using Blazorise;
using NetliveComponents.Models;

namespace NetliveComponents.Mapper.Tailwind;

public static class BlazoriseMapper
{
    public static Color GetBlazoriseColor(NetliveColor netliveColor)
    {
        return netliveColor.Name switch
        {
            "primary" => Color.Primary,
            "secondary" => Color.Secondary,
            "success" => Color.Success,
            "danger" => Color.Danger,
            "warning" => Color.Warning,
            "info" => Color.Info,
            "light" => Color.Light,
            "dark" => Color.Dark,
            "link" => Color.Link,
            _ => Color.Default,
        };
    }

    public static TextColor GetBlazoriseTextColor(NetliveTextColor netliveTextColor)
    {
        return netliveTextColor.Name switch
        {
            "primary" => TextColor.Primary,
            "secondary" => TextColor.Secondary,
            "success" => TextColor.Success,
            "danger" => TextColor.Danger,
            "warning" => TextColor.Warning,
            "info" => TextColor.Info,
            "light" => TextColor.Light,
            "dark" => TextColor.Dark,
            "white" => TextColor.White,
            "white50" => TextColor.White50,
            _ => TextColor.Default,
        };
    }

    public static Size GetBlazoriseSize(NetliveSize netliveSize)
    {
        return netliveSize switch
        {
            NetliveSize.Default => Size.Default,
            NetliveSize.ExtraSmall => Size.ExtraSmall,
            NetliveSize.Small => Size.Small,
            NetliveSize.Medium => Size.Medium,
            NetliveSize.Large => Size.Large,
            NetliveSize.ExtraLarge => Size.ExtraLarge,
            _ => Size.Default,
        };
    }

    public static ModalSize GetBlazoriseModalSize(NetliveModalSize netliveModalSize)
    {
        return netliveModalSize switch
        {
            NetliveModalSize.Default => ModalSize.Default,
            NetliveModalSize.Small => ModalSize.Small,
            NetliveModalSize.Large => ModalSize.Large,
            NetliveModalSize.ExtraLarge => ModalSize.ExtraLarge,
            NetliveModalSize.Fullscreen => ModalSize.Fullscreen,
            _ => ModalSize.Default,
        };
    }

    public static HeadingSize GetBlazoriseHeadingSize(NetliveHeadingSize netliveHeadingSize)
    {
        return netliveHeadingSize switch
        {
            NetliveHeadingSize.H1 => HeadingSize.Is1,
            NetliveHeadingSize.H2 => HeadingSize.Is2,
            NetliveHeadingSize.H3 => HeadingSize.Is3,
            NetliveHeadingSize.H4 => HeadingSize.Is4,
            NetliveHeadingSize.H5 => HeadingSize.Is5,
            NetliveHeadingSize.H6 => HeadingSize.Is6,
            _ => HeadingSize.Is5,
        };
    }

    public static TextRole GetBlazoriseInputType(NetliveInputType netliveInputType)
    {
        return netliveInputType switch
        {
            NetliveInputType.Text => TextRole.Text,
            NetliveInputType.Email => TextRole.Email,
            NetliveInputType.Password => TextRole.Password,
            NetliveInputType.Url => TextRole.Url,
            NetliveInputType.Search => TextRole.Search,
            NetliveInputType.Telephone => TextRole.Telephone,
            _ => TextRole.Text,
        };
    }

    public static ButtonType GetBlazoriseButtonType(NetliveButtonType netliveButtonType)
    {
        return netliveButtonType switch
        {
            NetliveButtonType.Button => ButtonType.Button,
            NetliveButtonType.Submit => ButtonType.Submit,
            NetliveButtonType.Reset => ButtonType.Reset,
            NetliveButtonType.Link => ButtonType.Link,
            _ => ButtonType.Button,
        };
    }

    public static IconSize GetBlazoriseIconSize(NetliveIconSize netliveIconSize)
    {
        return netliveIconSize switch
        {
            NetliveIconSize.Default => IconSize.Default,
            NetliveIconSize.ExtraSmall => IconSize.ExtraSmall,
            NetliveIconSize.Small => IconSize.Small,
            NetliveIconSize.Large => IconSize.Large,
            NetliveIconSize.x2 => IconSize.x2,
            NetliveIconSize.x3 => IconSize.x3,
            NetliveIconSize.x4 => IconSize.x4,
            NetliveIconSize.x5 => IconSize.x5,
            NetliveIconSize.x6 => IconSize.x6,
            NetliveIconSize.x7 => IconSize.x7,
            NetliveIconSize.x8 => IconSize.x8,
            NetliveIconSize.x9 => IconSize.x9,
            NetliveIconSize.x10 => IconSize.x10,
            _ => IconSize.Default,
        };
    }

    public static ToastPlacement GetBlazoriseToastPlacement(NetliveToastPlacement netliveToastPlacement)
    {
        return netliveToastPlacement switch
        {
            NetliveToastPlacement.Top => ToastPlacement.Top,
            NetliveToastPlacement.TopStart => ToastPlacement.TopStart,
            NetliveToastPlacement.TopEnd => ToastPlacement.TopEnd,
            NetliveToastPlacement.Bottom => ToastPlacement.Bottom,
            NetliveToastPlacement.BottomStart => ToastPlacement.BottomStart,
            NetliveToastPlacement.BottomEnd => ToastPlacement.BottomEnd,
            _ => ToastPlacement.Top,
        };
    }

    public static ToasterPlacement GetBlazoriseToasterPlacement(NetliveToasterPlacement netliveToasterPlacement)
    {
        return netliveToasterPlacement switch
        {
            NetliveToasterPlacement.Top => ToasterPlacement.Top,
            NetliveToasterPlacement.TopStart => ToasterPlacement.TopStart,
            NetliveToasterPlacement.TopEnd => ToasterPlacement.TopEnd,
            NetliveToasterPlacement.Bottom => ToasterPlacement.Bottom,
            NetliveToasterPlacement.BottomStart => ToasterPlacement.BottomStart,
            NetliveToasterPlacement.BottomEnd => ToasterPlacement.BottomEnd,
            _ => ToasterPlacement.Top,
        };
    }

    public static ToastIntent GetNetliveToastIntent(NetliveToastIntent netliveToastIntent)
    {
        return netliveToastIntent switch
        {
            NetliveToastIntent.Default => ToastIntent.Default,
            NetliveToastIntent.Info => ToastIntent.Info,
            NetliveToastIntent.Success => ToastIntent.Success,
            NetliveToastIntent.Warning => ToastIntent.Warning,
            NetliveToastIntent.Error => ToastIntent.Error,
            _ => ToastIntent.Default,
        };
    }

    public static object GetBlazoriseIconName(object netliveIconName)
    {
        return netliveIconName switch
        {
            NetliveIconName.Add => IconName.Add,
            NetliveIconName.Adjust => IconName.Adjust,
            NetliveIconName.Alert => IconName.ExclamationCircle,
            NetliveIconName.AlertOff => IconName.BellSlash,
            NetliveIconName.AlignCenter => IconName.AlignCenter,
            NetliveIconName.AlignJustify => IconName.AlignJustify,
            NetliveIconName.AlignLeft => IconName.AlignLeft,
            NetliveIconName.AlignRight => IconName.AlignRight,
            NetliveIconName.AngleDown => IconName.AngleDown,
            NetliveIconName.AngleLeft => IconName.AngleLeft,
            NetliveIconName.AngleRight => IconName.AngleRight,
            NetliveIconName.AngleUp => IconName.AngleUp,
            NetliveIconName.Apple => IconName.Apple,
            NetliveIconName.Archive => IconName.Archive,
            NetliveIconName.ArrowAltCircleDown => IconName.ArrowAltCircleDown,
            NetliveIconName.ArrowDown => IconName.ArrowDown,
            NetliveIconName.ArrowLeft => IconName.ArrowLeft,
            NetliveIconName.ArrowRight => IconName.ArrowRight,
            NetliveIconName.ArrowUp => IconName.ArrowUp,
            NetliveIconName.Baby => IconName.Baby,
            NetliveIconName.BabyCarriage => IconName.BabyCarriage,
            NetliveIconName.Backspace => IconName.Backspace,
            NetliveIconName.Backward => IconName.Backward,
            NetliveIconName.BalanceScale => IconName.BalanceScale,
            NetliveIconName.Ban => IconName.Ban,
            NetliveIconName.BandAid => IconName.BandAid,
            NetliveIconName.Bars => IconName.Bars,
            NetliveIconName.BatteryFull => IconName.BatteryFull,
            NetliveIconName.Bell => IconName.Bell,
            NetliveIconName.BellSlash => IconName.BellSlash,
            NetliveIconName.Biking => IconName.Biking,
            NetliveIconName.BirthdayCake => IconName.BirthdayCake,
            NetliveIconName.Bold => IconName.Bold,
            NetliveIconName.Bolt => IconName.Bolt,
            NetliveIconName.Book => IconName.Book,
            NetliveIconName.Bookmark => IconName.Bookmark,
            NetliveIconName.BookReader => IconName.BookReader,
            NetliveIconName.BorderAll => IconName.BorderAll,
            NetliveIconName.BorderNone => IconName.BorderNone,
            NetliveIconName.BorderStyle => IconName.BorderStyle,
            NetliveIconName.Briefcase => IconName.Briefcase,
            NetliveIconName.Brush => IconName.Brush,
            NetliveIconName.Bug => IconName.Bug,
            NetliveIconName.Building => IconName.Building,
            NetliveIconName.Bus => IconName.Bus,
            NetliveIconName.Calendar => IconName.Calendar,
            NetliveIconName.CalendarCheck => IconName.CalendarCheck,
            NetliveIconName.CalendarDay => IconName.CalendarDay,
            NetliveIconName.CalendarTimes => IconName.CalendarTimes,
            NetliveIconName.CalendarWeek => IconName.CalendarWeek,
            NetliveIconName.Camera => IconName.Camera,
            NetliveIconName.CameraRetro => IconName.CameraRetro,
            NetliveIconName.Car => IconName.Car,
            NetliveIconName.CaretSquareRight => IconName.CaretSquareRight,
            NetliveIconName.Cart => IconName.ShoppingCart,
            NetliveIconName.CartMinus => IconName.CartMinus,
            NetliveIconName.CartPlus => IconName.CartPlus,
            NetliveIconName.Chair => IconName.Chair,
            NetliveIconName.ChartArea => IconName.ChartArea,
            NetliveIconName.ChartBar => IconName.ChartBar,
            NetliveIconName.ChartLine => IconName.ChartLine,
            NetliveIconName.ChartPie => IconName.ChartPie,
            NetliveIconName.ChartScatter => IconName.ChartScatter,
            NetliveIconName.Check => IconName.Check,
            NetliveIconName.CheckCircle => IconName.CheckCircle,
            NetliveIconName.CheckDouble => IconName.CheckDouble,
            NetliveIconName.CheckSquare => IconName.CheckSquare,
            NetliveIconName.ChevronDown => IconName.ChevronDown,
            NetliveIconName.ChevronLeft => IconName.ChevronLeft,
            NetliveIconName.ChevronRight => IconName.ChevronRight,
            NetliveIconName.ChevronUp => IconName.ChevronUp,
            NetliveIconName.Circle => IconName.Circle,
            NetliveIconName.City => IconName.City,
            NetliveIconName.Clear => IconName.Times,
            NetliveIconName.ClinicMedical => IconName.ClinicMedical,
            NetliveIconName.Clipboard => IconName.Clipboard,
            NetliveIconName.Clock => IconName.Clock,
            NetliveIconName.ClosedCaptioning => IconName.ClosedCaptioning,
            NetliveIconName.Cloud => IconName.Cloud,
            NetliveIconName.CloudDownloadAlt => IconName.CloudDownloadAlt,
            NetliveIconName.CloudUploadAlt => IconName.CloudUploadAlt,
            NetliveIconName.Cocktail => IconName.Cocktail,
            NetliveIconName.Code => IconName.Code,
            NetliveIconName.Coffee => IconName.Coffee,
            NetliveIconName.Comment => IconName.Comment,
            NetliveIconName.CommentAlt => IconName.CommentAlt,
            NetliveIconName.Comments => IconName.Comments,
            NetliveIconName.CompactDisc => IconName.CompactDisc,
            NetliveIconName.Compass => IconName.Compass,
            NetliveIconName.Compress => IconName.Compress,
            NetliveIconName.Copy => IconName.Copy,
            NetliveIconName.Copyright => IconName.Copyright,
            NetliveIconName.CreditCard => IconName.CreditCard,
            NetliveIconName.Crop => IconName.Crop,
            NetliveIconName.Cut => IconName.Cut,
            NetliveIconName.Dashboard => IconName.Dashboard,
            NetliveIconName.Delete => IconName.Delete,
            NetliveIconName.Desktop => IconName.Desktop,
            NetliveIconName.Dice => IconName.Dice,
            NetliveIconName.Directions => IconName.Directions,
            NetliveIconName.Dog => IconName.Dog,
            NetliveIconName.DollarSign => IconName.DollarSign,
            NetliveIconName.DotCircle => IconName.DotCircle,
            NetliveIconName.Download => IconName.Download,
            NetliveIconName.Dumbbell => IconName.Dumbbell,
            NetliveIconName.Edit => IconName.Edit,
            NetliveIconName.Eject => IconName.Eject,
            NetliveIconName.Ethernet => IconName.Ethernet,
            NetliveIconName.EuroSign => IconName.EuroSign,
            NetliveIconName.Exclamation => IconName.Exclamation,
            NetliveIconName.ExclamationCircle => IconName.ExclamationCircle,
            NetliveIconName.ExclamationTriangle => IconName.ExclamationTriangle,
            NetliveIconName.Expand => IconName.Expand,
            NetliveIconName.ExpandArrowsAlt => IconName.ExpandArrowsAlt,
            NetliveIconName.ExpandLess => IconName.ChevronUp,
            NetliveIconName.ExpandMore => IconName.ChevronDown,
            NetliveIconName.ExternalLinkSquareAlt => IconName.ExternalLinkSquareAlt,
            NetliveIconName.Eye => IconName.Eye,
            NetliveIconName.EyeSlash => IconName.EyeSlash,
            NetliveIconName.FastBackward => IconName.FastBackward,
            NetliveIconName.FastForward => IconName.FastForward,
            NetliveIconName.File => IconName.File,
            NetliveIconName.FileAlt => IconName.FileAlt,
            NetliveIconName.FileDownload => IconName.FileDownload,
            NetliveIconName.FilePdf => IconName.FilePdf,
            NetliveIconName.FileUpload => IconName.FileUpload,
            NetliveIconName.Film => IconName.Film,
            NetliveIconName.Filter => IconName.Filter,
            NetliveIconName.Fingerprint => IconName.Fingerprint,
            NetliveIconName.Fire => IconName.Fire,
            NetliveIconName.Flag => IconName.Flag,
            NetliveIconName.Flask => IconName.Flask,
            NetliveIconName.Folder => IconName.Folder,
            NetliveIconName.FolderOpen => IconName.FolderOpen,
            NetliveIconName.FolderPlus => IconName.FolderPlus,
            NetliveIconName.Forward => IconName.Forward,
            NetliveIconName.Frown => IconName.Frown,
            NetliveIconName.FrownOpen => IconName.FrownOpen,
            NetliveIconName.Gamepad => IconName.Gamepad,
            NetliveIconName.GasPump => IconName.GasPump,
            NetliveIconName.Gavel => IconName.Gavel,
            NetliveIconName.Gift => IconName.Gift,
            NetliveIconName.Globe => IconName.Globe,
            NetliveIconName.Grin => IconName.Grin,
            NetliveIconName.GripLines => IconName.GripLines,
            NetliveIconName.GripVertical => IconName.GripVertical,
            NetliveIconName.HandPaper => IconName.HandPaper,
            NetliveIconName.HandsHelping => IconName.HandsHelping,
            NetliveIconName.Headphones => IconName.Headphones,
            NetliveIconName.Headset => IconName.Headset,
            NetliveIconName.Heart => IconName.Heart,
            NetliveIconName.Highlighter => IconName.Highlighter,
            NetliveIconName.History => IconName.History,
            NetliveIconName.Home => IconName.Home,
            NetliveIconName.Hospital => IconName.Hospital,
            NetliveIconName.Hotel => IconName.Hotel,
            NetliveIconName.HotTub => IconName.HotTub,
            NetliveIconName.Hourglass => IconName.Hourglass,
            NetliveIconName.IdCard => IconName.IdCard,
            NetliveIconName.Image => IconName.Image,
            NetliveIconName.Images => IconName.Images,
            NetliveIconName.Inbox => IconName.Inbox,
            NetliveIconName.Indent => IconName.Indent,
            NetliveIconName.Infinity => IconName.Infinity,
            NetliveIconName.Info => IconName.Info,
            NetliveIconName.InfoCircle => IconName.InfoCircle,
            NetliveIconName.Italic => IconName.Italic,
            NetliveIconName.Key => IconName.Key,
            NetliveIconName.Keyboard => IconName.Keyboard,
            NetliveIconName.Language => IconName.Language,
            NetliveIconName.Laptop => IconName.Laptop,
            NetliveIconName.LaptopCode => IconName.LaptopCode,
            NetliveIconName.Laugh => IconName.Laugh,
            NetliveIconName.LayerGroup => IconName.LayerGroup,
            NetliveIconName.Lightbulb => IconName.Lightbulb,
            NetliveIconName.Link => IconName.Link,
            NetliveIconName.List => IconName.List,
            NetliveIconName.ListOl => IconName.ListOl,
            NetliveIconName.ListUl => IconName.ListUl,
            NetliveIconName.LocationArrow => IconName.LocationArrow,
            NetliveIconName.Lock => IconName.Lock,
            NetliveIconName.LockOpen => IconName.LockOpen,
            NetliveIconName.Mail => IconName.Mail,
            NetliveIconName.MailOpen => IconName.MailOpen,
            NetliveIconName.Map => IconName.Map,
            NetliveIconName.MapMarker => IconName.MapMarker,
            NetliveIconName.MapMarkerAlt => IconName.MapMarkerAlt,
            NetliveIconName.Memory => IconName.Memory,
            NetliveIconName.Microphone => IconName.Microphone,
            NetliveIconName.MicrophoneSlash => IconName.MicrophoneSlash,
            NetliveIconName.MinusCircle => IconName.MinusCircle,
            NetliveIconName.MinusSquare => IconName.MinusSquare,
            NetliveIconName.MoneyBillAlt => IconName.MoneyBillAlt,
            NetliveIconName.Moon => IconName.Moon,
            NetliveIconName.MoreVertical => IconName.MoreVertical,
            NetliveIconName.Motorcycle => IconName.Motorcycle,
            NetliveIconName.Mouse => IconName.Mouse,
            NetliveIconName.Music => IconName.Music,
            NetliveIconName.PaintBrush => IconName.PaintBrush,
            NetliveIconName.PaintRoller => IconName.PaintRoller,
            NetliveIconName.Palette => IconName.Palette,
            NetliveIconName.Paperclip => IconName.Paperclip,
            NetliveIconName.PaperPlane => IconName.PaperPlane,
            NetliveIconName.Parking => IconName.Parking,
            NetliveIconName.Paste => IconName.Paste,
            NetliveIconName.Pause => IconName.Pause,
            NetliveIconName.PauseCircle => IconName.PauseCircle,
            NetliveIconName.Pen => IconName.Pen,
            NetliveIconName.Phone => IconName.Phone,
            NetliveIconName.PhoneAlt => IconName.PhoneAlt,
            NetliveIconName.PizzaSlice => IconName.PizzaSlice,
            NetliveIconName.Plane => IconName.Plane,
            NetliveIconName.PlaneArrival => IconName.PlaneArrival,
            NetliveIconName.PlaneDeparture => IconName.PlaneDeparture,
            NetliveIconName.Play => IconName.Play,
            NetliveIconName.PlayCircle => IconName.PlayCircle,
            NetliveIconName.Plug => IconName.Plug,
            NetliveIconName.PlusCircle => IconName.PlusCircle,
            NetliveIconName.PlusSquare => IconName.PlusSquare,
            NetliveIconName.Poll => IconName.Poll,
            NetliveIconName.Portrait => IconName.Portrait,
            NetliveIconName.Print => IconName.Print,
            NetliveIconName.PuzzlePiece => IconName.PuzzlePiece,
            NetliveIconName.QuestionCircle => IconName.QuestionCircle,
            NetliveIconName.QuoteRight => IconName.QuoteRight,
            NetliveIconName.Random => IconName.Random,
            NetliveIconName.Receipt => IconName.Receipt,
            NetliveIconName.Redo => IconName.Redo,
            NetliveIconName.Remove => IconName.Times,
            NetliveIconName.RemoveFormat => IconName.RemoveFormat,
            NetliveIconName.Reply => IconName.Reply,
            NetliveIconName.ReplyAll => IconName.ReplyAll,
            NetliveIconName.Restroom => IconName.Restroom,
            NetliveIconName.Rss => IconName.Rss,
            NetliveIconName.RulerHorizontal => IconName.RulerHorizontal,
            NetliveIconName.Running => IconName.Running,
            NetliveIconName.Satellite => IconName.Satellite,
            NetliveIconName.Save => IconName.Save,
            NetliveIconName.School => IconName.School,
            NetliveIconName.Screenshot => IconName.Desktop,
            NetliveIconName.SdCard => IconName.SdCard,
            NetliveIconName.Search => IconName.Search,
            NetliveIconName.SearchMinus => IconName.SearchMinus,
            NetliveIconName.SearchPlus => IconName.SearchPlus,
            NetliveIconName.Seedling => IconName.Seedling,
            NetliveIconName.Send => IconName.PaperPlane,
            NetliveIconName.Server => IconName.Server,
            NetliveIconName.Settings => IconName.Settings,
            NetliveIconName.Shapes => IconName.Shapes,
            NetliveIconName.Share => IconName.Share,
            NetliveIconName.ShareAlt => IconName.ShareAlt,
            NetliveIconName.Shield => IconName.Shield,
            NetliveIconName.ShieldAlt => IconName.ShieldAlt,
            NetliveIconName.Ship => IconName.Ship,
            NetliveIconName.ShoppingBag => IconName.ShoppingBag,
            NetliveIconName.ShoppingBasket => IconName.ShoppingBasket,
            NetliveIconName.ShoppingCart => IconName.ShoppingCart,
            NetliveIconName.ShuttleVan => IconName.ShuttleVan,
            NetliveIconName.SimCard => IconName.SimCard,
            NetliveIconName.SliderHorizontal => IconName.SliderHorizontal,
            NetliveIconName.Smartphone => IconName.Smartphone,
            NetliveIconName.Smile => IconName.Smile,
            NetliveIconName.Smoking => IconName.Smoking,
            NetliveIconName.SmokingBan => IconName.SmokingBan,
            NetliveIconName.Sms => IconName.CommentAlt,
            NetliveIconName.Snowflake => IconName.Snowflake,
            NetliveIconName.Sort => IconName.Sort,
            NetliveIconName.SortAlphaDown => IconName.SortAlphaDown,
            NetliveIconName.SortAlphaUp => IconName.SortAlphaUp,
            NetliveIconName.SortAmountDownAlt => IconName.SortAmountDownAlt,
            NetliveIconName.SortDown => IconName.SortDown,
            NetliveIconName.SortUp => IconName.SortUp,
            NetliveIconName.Spa => IconName.Spa,
            NetliveIconName.SpellCheck => IconName.SpellCheck,
            NetliveIconName.Square => IconName.Square,
            NetliveIconName.Star => IconName.Star,
            NetliveIconName.StarHalf => IconName.StarHalf,
            NetliveIconName.StepBackward => IconName.StepBackward,
            NetliveIconName.StepForward => IconName.StepForward,
            NetliveIconName.StickyNote => IconName.StickyNote,
            NetliveIconName.Stop => IconName.Stop,
            NetliveIconName.Store => IconName.Store,
            NetliveIconName.StoreAlt => IconName.StoreAlt,
            NetliveIconName.Stream => IconName.Stream,
            NetliveIconName.StreetView => IconName.StreetView,
            NetliveIconName.Strikethrough => IconName.Strikethrough,
            NetliveIconName.Subscript => IconName.Subscript,
            NetliveIconName.Subway => IconName.Subway,
            NetliveIconName.Suitcase => IconName.Suitcase,
            NetliveIconName.Sun => IconName.Sun,
            NetliveIconName.Superscript => IconName.Superscript,
            NetliveIconName.SwimmingPool => IconName.SwimmingPool,
            NetliveIconName.Sync => IconName.Sync,
            NetliveIconName.SyncAlt => IconName.SyncAlt,
            NetliveIconName.Table => IconName.Table,
            NetliveIconName.Tablet => IconName.Tablet,
            NetliveIconName.Tag => IconName.Tag,
            NetliveIconName.Taxi => IconName.Taxi,
            NetliveIconName.TextHeight => IconName.TextHeight,
            NetliveIconName.ThumbsDown => IconName.ThumbsDown,
            NetliveIconName.ThumbsUp => IconName.ThumbsUp,
            NetliveIconName.Ticket => IconName.Ticket,
            NetliveIconName.TicketAlt => IconName.TicketAlt,
            NetliveIconName.Times => IconName.Times,
            NetliveIconName.TimesCircle => IconName.TimesCircle,
            NetliveIconName.Tint => IconName.Tint,
            NetliveIconName.TintSlash => IconName.TintSlash,
            NetliveIconName.TrafficLight => IconName.TrafficLight,
            NetliveIconName.Train => IconName.Train,
            NetliveIconName.Tram => IconName.Tram,
            NetliveIconName.Tree => IconName.Tree,
            NetliveIconName.Truck => IconName.Truck,
            NetliveIconName.Tv => IconName.Tv,
            NetliveIconName.UmbrellaBeach => IconName.UmbrellaBeach,
            NetliveIconName.Underline => IconName.Underline,
            NetliveIconName.Undo => IconName.Undo,
            NetliveIconName.Unlock => IconName.Unlock,
            NetliveIconName.User => IconName.User,
            NetliveIconName.UserCheck => IconName.UserCheck,
            NetliveIconName.UserCircle => IconName.UserCircle,
            NetliveIconName.UserFriends => IconName.UserFriends,
            NetliveIconName.UserPlus => IconName.UserPlus,
            NetliveIconName.Users => IconName.Users,
            NetliveIconName.UserTie => IconName.UserTie,
            NetliveIconName.Utensils => IconName.Utensils,
            NetliveIconName.Video => IconName.Video,
            NetliveIconName.VideoSlash => IconName.VideoSlash,
            NetliveIconName.Voicemail => IconName.Voicemail,
            NetliveIconName.VolumeDown => IconName.VolumeDown,
            NetliveIconName.VolumeMute => IconName.VolumeMute,
            NetliveIconName.VolumeOff => IconName.VolumeOff,
            NetliveIconName.VolumeUp => IconName.VolumeUp,
            NetliveIconName.Walking => IconName.Walking,
            NetliveIconName.Wallet => IconName.Wallet,
            NetliveIconName.Wheelchair => IconName.Wheelchair,
            NetliveIconName.Wifi => IconName.Wifi,
            NetliveIconName.WineBottle => IconName.WineBottle,
            NetliveIconName.Wrench => IconName.Wrench,
            NetliveIconName.Zoom => IconName.Search,
            NetliveIconName.ZoomIn => IconName.SearchPlus,
            NetliveIconName.ZoomOut => IconName.SearchMinus,
            // Custom
            NetliveIconName.DotsVertical => "fa-ellipsis-vertical",
            NetliveIconName.Spinner => "fa-spinner",
            _ => IconName.Add // Default case
        };
    }

}
